development:
  adapter: postgresql
  encoding: utf8
  database: haiku_hitmen_development
  pool: 5

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: haiku_hitmen_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: haiku_hitmen_production
  pool: 5